# Generated by Django 5.2.8 on 2025-11-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_data',
            field=models.TextField(blank=True, default='', verbose_name='Данные заявления'),
        ),
    ]
